/* globals IDSAutocomplete */
const init = () => {
  const autocompleteStringComponents = document.querySelectorAll('.if.autocomplete:not(.search-field):not(.tags)');
  const suggestions = [
    'how do i convert to pdf',
    'how do i convert to muslim',
    'how do i convert to judaism',
    'how do i convert to christianity',
    'how do i convert to catholic',
    'how do i convert to mp3'
  ];

  autocompleteStringComponents.forEach(el => {
    IDSAutocomplete.string.init(el, {
      suggestions,
      charLimit: 3
    });
  });

  const autocompleteTagComponents = document.querySelectorAll('.if.autocomplete.tags:not(.search-field)');
  const suggestedTags = [
    'tentation',
    'decolonise',
    'roxburgh',
    'apocentricity',
    'overimitative',
    'grappelli',
    'ragfish',
    'donatus',
    'kerkyra',
    'kwame',
    'superfecundation',
    'nonhematic',
    'rabic',
    'bravissimo',
    'ochlocratic',
    'moronism',
    'svelter',
    'estimate',
    'cognatic',
    'lucretia',
    'jangler',
    'comminating',
    'moanful',
    'homosporous',
    'brawl',
    'underman',
    'mopes',
    'mountebank',
    'sallied',
    'jiglike',
    'certified',
    'pyrheliometric',
    'discourteous',
    'lutetium',
    'paraphrase',
    'immovableness',
    'psychoanalyse',
    'slaw',
    'predelegate',
    'conditioned',
    'unministered',
    'wolseley',
    'oxime',
    'austria',
    'heroical',
    'noncondensable',
    'nonperpendicular',
    'cullied',
    'undeclaimed',
    'colorfast',
    'bladderwrack',
    'camphire',
    'preinhered',
    'foreglimpse',
    'dissymmetrically',
    'apocryphal',
    'cetus',
    'rioter',
    'octonary',
    'glycemic',
    'unpromotable',
    'unhistorical',
    'underran',
    'roselle',
    'imbrium',
    'skinneries',
    'spunware',
    'soirée',
    'snohomish',
    'crow',
    'unnasal',
    'cypriot',
    'slot',
    'amphitruo',
    'ecchymotic',
    'homolecithal',
    'befogged',
    'cardboard',
    'chock',
    'angelican',
    'conciliable',
    'skyphos',
    'nanette',
    'lazarette',
    'trimer',
    'chessel',
    'delsartian',
    'lore',
    'heap',
    'frizzier',
    'reabandon',
    'boatman',
    'belar',
    'adjacence',
    'horsemint',
    'prebenefit',
    'lymphangial',
    'wriggler',
    'atomism',
    'untransported'
  ];

  autocompleteTagComponents.forEach(el => {
    IDSAutocomplete.tag.init(el, { suggestions: suggestedTags, charLimit: 3 });
  });
};

export default init;
